const {chromium}=require('playwright');
const assert=require('node:assert/strict');const http=require('node:http');const fs=require('node:fs');const path=require('node:path');
const root=path.resolve('web');const server=http.createServer((req,res)=>{const pathname=new URL(req.url,'http://localhost').pathname;const file=path.resolve(root,'.'+(pathname==='/'?'/index.html':pathname));if(!file.startsWith(root+path.sep)){res.writeHead(403);return res.end()}try{const content=fs.readFileSync(file);res.setHeader('Content-Type',file.endsWith('.js')?'text/javascript':file.endsWith('.css')?'text/css':file.endsWith('.json')?'application/json':'text/html');res.end(content)}catch{res.writeHead(404);res.end()}});
(async()=>{await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const url=process.env.DATRIXON_BASE_URL?.replace(/\/$/,'')||`http://127.0.0.1:${server.address().port}`;const browser=await chromium.launch({headless:true,...(process.env.NORTHSTAR_BROWSER_CHANNEL?{channel:process.env.NORTHSTAR_BROWSER_CHANNEL}:{})});try{
 const page=await browser.newPage({viewport:{width:1440,height:1000}});const errors=[];const allowCDN=process.env.DATRIXON_ALLOW_CDN==='1';page.on('pageerror',e=>errors.push(e.message));
 // Exercise the public application's graceful CDN fallback deterministically.
 await page.route('**/*',route=>(route.request().url().startsWith(url)||allowCDN)?route.continue():route.abort());
 await page.goto(url);await page.waitForSelector('.trust-reconciliation',{state:'attached'});await page.waitForSelector('body:not(.is-loading)');
 const payload=process.env.DATRIXON_BASE_URL?await (await page.request.get(url+'/data/dashboard.json')).json():JSON.parse(fs.readFileSync(path.join(root,'data/dashboard.json'),'utf8'));
 assert.match(await page.title(),/Datrixon/);if(allowCDN)assert(await page.evaluate(()=>!!window.echarts),'ECharts loaded for normal-CDN verification');
 assert.deepEqual(await page.locator('a[href^="#"]').evaluateAll(links=>links.map(a=>a.getAttribute('href')).filter(href=>href.length>1&&!document.getElementById(href.slice(1)))),[],'Every internal link resolves');assert.equal(payload.pipeline_metadata.publication_status,'APPROVED');assert(await page.locator('#trend svg,#trend canvas').count()>0);assert(await page.locator('#margin-chart svg,#margin-chart canvas').count()>0);
 for(const [key,coverage] of Object.entries(payload.extract_coverage)){
  const table=page.locator(`[data-extract="${key}"]`);
  assert.equal(await table.count(),1,`Table identity ${key}`);
  assert((await table.locator('.coverage-note').textContent()).includes(coverage.selection),`Coverage ${key}`);
 }
 await page.locator('.signal-card[data-focus^="V"]').click();
 assert.equal(await page.locator('[data-extract="vendor_performance"] input').inputValue(),payload.business_findings.supplier_deterioration.VendorID);
 assert.match(await page.locator('.period').textContent(),/Purchasing snapshot/);
 await page.locator('.sidebar a[href="#overview"]').click();
 assert.equal(await page.locator('.signal-card').count(),5);assert.match(await page.locator('#performance-summary').textContent(),/Revenue/);if(payload.decision_evidence)assert.equal(await page.locator('.placeholder-section .decision-summary').count(),5);assert.equal(await page.locator('.kpi-sparkline').count(),8);
 await page.selectOption('#date-from','2024-11');await page.selectOption('#date-to','2025-02');assert.notEqual(await page.locator('#yoy').textContent(),'—');const revenue=await page.locator('#revenue').textContent();await page.selectOption('#date-from','2025-12');assert.equal(await page.locator('#revenue').textContent(),revenue);assert.match(await page.locator('#filter-error').textContent(),/last valid/);
 await page.locator('.sidebar a[href="#quality"]').click();assert(!(await page.locator('.trust-reconciliation tbody tr').filter({hasText:'Units'}).textContent()).includes('$'));
 await page.locator('.sidebar a[href="#project-story"]').click();await page.waitForSelector('#project-story:visible');await page.locator('[data-stage="3"]').click();assert.equal(await page.locator('.schema-columns a').count(),10);
 await page.goto(url+'/#enterprise-roadmap');await page.waitForSelector('#enterprise-roadmap:visible');assert.match(await page.locator('#enterprise-roadmap').textContent(),/future requirements/);
 await page.locator('.sidebar a[href="#customers"]').click();await page.locator('#customers .data-table-card input').first().fill('no-match-value');assert(await page.locator('#customers .table-empty').isVisible());
 await page.locator('#customers .data-table-card input').first().fill('');await page.locator('#customers .sort-button').first().focus();await page.keyboard.press('Enter');assert.equal(await page.locator('#customers th').first().getAttribute('aria-sort'),'ascending');
 const download=page.waitForEvent('download');await page.locator('#customers .csv-button').first().click();const exported=await download;assert(exported.suggestedFilename().endsWith('.csv'));const csv=fs.readFileSync(await exported.path(),'utf8');assert.equal(csv.trimEnd().split(/\r?\n/).length-1,payload.customer_performance.length,'CSV has complete displayed customer extract');
 for(const width of [390,768,1440]){await page.setViewportSize({width,height:900});await page.goto(url);await page.waitForSelector('.signal-card');assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));for(const route of ['sales','customers','inventory','purchasing','operations','quality','project-story','architecture','enterprise-roadmap']){await page.goto(url+'/#'+route);assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),`Overflow ${width} ${route}`)}if(width===390){await page.selectOption('#mobile-nav','#project-story');await page.waitForSelector('#project-story:visible');assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth))}}
 await page.route('**/*',route=>route.request().url().includes('/data/dashboard.json')?route.fulfill({status:503,body:'Unavailable'}):(route.request().url().startsWith(url)||allowCDN)?route.continue():route.abort());
 await page.goto(url+'/?failure=1#project-story');await page.waitForSelector('.load-error',{state:'attached'});assert(await page.locator('#project-story').isVisible());assert.equal(await page.locator('.hero-status b').textContent(),'Data unavailable');assert.deepEqual(errors,[]);
 console.log('PASS: period correctness, scope, reconciliation units, routes, sorting, CSV, responsive UI, CDN fallback, data failure with accessible documentation');
 }finally{await browser.close();server.close()}})().catch(e=>{console.error(e);server.close();process.exitCode=1});
