/* V2 views reuse the approved V1 data artifact and the existing navigation shell. */
const governanceRoutes={'trust-center':'Trust Center',reconciliation:'Reconciliation','metric-catalog':'Metric Catalog','data-catalog':'Data Products',lineage:'Data Lineage',contracts:'Source Contracts',glossary:'Business Glossary','ai-readiness':'AI Readiness','ai-assistant':'Governed Assistant','audit-evidence':'Audit & Evidence',incidents:'Failure Simulator'};
function mountGovernance(){
 const nav=document.querySelector('.sidebar nav'),anchor=nav.querySelector('[href="#quality"]');
 anchor.insertAdjacentHTML('beforebegin','<div class="nav-group">TRUST & GOVERNANCE</div>');
 for(const [id,title] of Object.entries(governanceRoutes)){
   const section=document.createElement('section');section.id=id;section.className='content governance-page';section.hidden=true;
   section.innerHTML=`<header class="governance-heading"><span class="eyebrow">DATRIXON V2 · GOVERNED ERP INTELLIGENCE</span><h1>${title}</h1></header><div class="governance-body"><p role="status">Governance evidence loads with the approved dataset. If loading fails, retry the application; Project &amp; Architecture remains accessible.</p></div>`;
   document.querySelector('main').append(section);
   const a=document.createElement('a');a.href='#'+id;a.innerHTML=`<i aria-hidden="true">${id==='ai-assistant'?'⌕':'◇'}</i>${title}`;nav.append(a);
 }
 nav.insertBefore(nav.querySelector('[href="#trust-center"]'),anchor);
}
function renderGovernance(data){
 const g=data.governance;if(!g)return;
 const api=DatrixonAI,escape=h,metrics=g.registry.metrics;
 const body=id=>document.querySelector('#'+id+' .governance-body');
 const badge=status=>`<span class="gov-badge ${['PASS','TRUSTED','Ready','ALLOW','CERTIFIED_DEMO','ANSWERED'].includes(status)?'good':['FAIL','BLOCKED','Blocked','DENY','DRAFT'].includes(status)?'bad':'warn'}">${escape(status)}</span>`;
 const json=value=>`<pre class="gov-json">${escape(JSON.stringify(value,null,2))}</pre>`;
 const table=(rows,columns)=>`<div class="gov-table-scroll" tabindex="0" role="region" aria-label="Scrollable evidence table"><table class="gov-table"><thead><tr>${columns.map(([k,label])=>`<th scope="col">${escape(label||k)}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${columns.map(([key])=>`<td>${escape(typeof r[key]==='object'?JSON.stringify(r[key]):r[key])}</td>`).join('')}</tr>`).join('')||`<tr><td colspan="${columns.length}">No matching evidence.</td></tr>`}</tbody></table></div>`;
 const detail=(title,content)=>`<details class="gov-detail"><summary>${escape(title)}</summary>${content}</details>`;
 const stamp=`<p class="gov-context">Synthetic data · business cutoff ${escape(g.version_identity.business_cutoff)} · approved ${escape(g.version_identity.timestamp)}. Batch freshness is separate from business time.</p>`;
 const link=(route,label)=>`<a href="#${route}">${escape(label)} →</a>`;
 const session=[];
 function log(event,result){session.push({timestamp:new Date().toISOString(),event,decision:result.policy_decision||result.decision,answer_id:result.answer_id,metric_ids:result.metric_ids,simulation:result.simulation||false});renderAudit()}
 function renderAudit(){body('audit-evidence').innerHTML=stamp+`<h2>Approved build events</h2><p>Local pipeline evidence. Browser interaction events are session-only and disappear on reload; questions and record values are excluded from the event log. This is not a tamper-proof security audit.</p>`+table(g.audit,[['timestamp','Time'],['event','Event'],['status','Status'],['asset','Asset']])+`<h2>Current browser session</h2>`+table(session,[['timestamp','Time'],['event','Event'],['decision','Decision'],['metric_ids','Metrics'],['simulation','Simulation']])+detail('Data version and hashes',json(g.version_identity))+`<p>Exact publication bytes and SHA-256 are retained in the matching run_manifest.json within the local run bundle, or the downloadable refresh artifact when built in GitHub Actions. A file cannot contain its own final hash.</p>`}
 function renderTrustCenter(){
   const decisions=metrics.filter(m=>m.certification_status==='CERTIFIED_DEMO').map(m=>api.decision(g,m.metric_id));
   const blocked=decisions.filter(d=>d.status==='BLOCKED');
   body('trust-center').innerHTML=stamp+`<div class="gov-summary"><div><span>Approved data product state</span><h2>${badge(blocked.length?'BLOCKED':decisions.some(d=>d.status==='WARNING')?'WARNING':'TRUSTED')}</h2><p>Last approved dataset remains available. Stale data blocks new assistant answers; historical analytics retain their cutoff disclosure.</p></div><div><strong>${decisions.length}</strong><span>Certified demo metrics</span><strong>${blocked.length}</strong><span>Blocked at query time</span></div></div><div class="gov-grid">`+
   ['schema','quality','reconciliation','metric_certification','contract','freshness','lineage','access_policy'].map(key=>{const statuses=decisions.map(d=>d.controls[key]);const state=statuses.includes('FAIL')?'FAIL':statuses.includes('WARNING')?'WARNING':'PASS';return `<article class="gov-card"><h3>${escape(key.replaceAll('_',' '))}</h3>${badge(state)}<p>${key==='access_policy'?'Policy coverage checked. Role switching is a public demonstration, not authentication.':key==='freshness'?'Weekly refresh + 24-hour grace. Historical business cutoff is separately disclosed.':key==='quality'?'Expected synthetic negative stock is acknowledged explicitly.':'Mandatory evidence is evaluated before publishing certified metrics.'}</p></article>`}).join('')+`</div><h2>Decisions by metric</h2>`+table(metrics.map(m=>({Metric:m.display_name,...api.decision(g,m.metric_id)})),[['Metric','Metric'],['status','Trust'],['failed_controls','Blocking reasons']])+`<p>Draft definitions are intentionally blocked. Their existence does not block certified data products. ${link('ai-readiness','Inspect readiness')} ${link('incidents','Demonstrate a failure')}</p>`;
 }
 function selectMetric(id='revenue'){
   const m=metrics.find(m=>m.metric_id===id)||metrics[0],value=g.values[m.metric_id],trust=api.decision(g,m.metric_id);
   document.querySelector('#metric-select').value=m.metric_id;
   document.querySelector('#metric-detail').innerHTML=`<div class="gov-card"><div class="gov-card-heading"><h2>${escape(m.display_name)}</h2>${badge(m.certification_status)} ${badge(trust.status)}</div><p>${escape(m.business_definition)}</p><strong class="gov-value">${value?escape(api.format(value.value,m.unit)):'Unavailable — definition requires approval'}</strong><dl class="gov-facts">${[['Business owner',m.owner],['Technical steward',m.steward],['Grain',m.grain],['Cadence',m.refresh_frequency],['Version',m.version],['Sensitivity',m.sensitivity],['Roles',m.permitted_roles.join(', ')],['Sources',m.source_tables.join(', ')],['Reconciliation',m.reconciliation_rule.join(', ')||'Source controls + semantic query; no independent three-way reconciliation claimed'],['Downstream usage',m.downstream_consumers.join(', ')]].map(([k,v])=>`<div><dt>${escape(k)}</dt><dd>${escape(v)}</dd></div>`).join('')}</dl>${detail('Executable formula and governance contract',json(m))}${detail('Trust evidence',json(trust))}<button type="button" id="metric-lineage">Trace this metric →</button></div>`;
   document.querySelector('#metric-lineage').onclick=()=>{document.querySelector('#lineage-select').value=m.metric_id;renderGraph(m.metric_id);location.hash='#lineage'};
 }
 body('metric-catalog').innerHTML=stamp+`<p>Definitions are certified for this demonstration, not signed off by a corporate Finance function. Unresolved business definitions remain drafts and cannot answer questions.</p><label class="gov-field">Select governed metric<select id="metric-select">${metrics.map(m=>`<option value="${m.metric_id}">${escape(m.display_name)}</option>`).join('')}</select></label><div id="metric-detail"></div>`;
 document.querySelector('#metric-select').onchange=e=>selectMetric(e.target.value);
 function renderGraph(id){
   const edges=g.lineage.filter(e=>e.metric===id),nodes=[...new Set(edges.flatMap(e=>[e.upstream_asset,e.downstream_asset]))];
   const groups=[['Source fields',n=>n.startsWith('raw:')],['Normalized staging',n=>n.startsWith('staging:')],['Warehouse fields',n=>!n.includes(':')],['Semantic metric',n=>n.startsWith('metric:')],['Consumers',n=>/^(dashboard|catalog|ai):/.test(n)]];
   document.querySelector('#lineage-graph').innerHTML=`<div class="gov-lineage">${groups.map(([title,filter],i)=>`<section><h3>${escape(title)}</h3>${nodes.filter(filter).map(n=>`<button type="button" class="gov-node" data-asset="${escape(n)}">${escape(n)}</button>`).join('')||'<p>No certified dependencies</p>'}${i<4?'<span class="gov-arrow" aria-hidden="true">→</span>':''}</section>`).join('')}</div><p>Edges come from executed SQLite column reads plus reviewed loader mappings. Select a node to inspect downstream impact.</p><div id="impact-detail" aria-live="polite"></div>${detail('Transformation edges and modules',table(edges,[['upstream_asset','Upstream'],['downstream_asset','Downstream'],['transformation','Transformation'],['module','Module']]))}`;
   document.querySelectorAll('#lineage-graph [data-asset]').forEach(button=>button.onclick=()=>{document.querySelector('#impact-detail').innerHTML=`<h3>Change impact: ${escape(button.dataset.asset)}</h3>`+json(api.impact(g.lineage,button.dataset.asset))});
 }
 body('lineage').innerHTML=stamp+`<label class="gov-field">Trace metric<select id="lineage-select">${metrics.map(m=>`<option value="${m.metric_id}">${escape(m.display_name)}</option>`).join('')}</select></label><div id="lineage-graph"></div>`;
 document.querySelector('#lineage-select').onchange=e=>renderGraph(e.target.value);renderGraph('revenue');selectMetric();
 body('data-catalog').innerHTML=stamp+`<div class="gov-grid">${g.products.map(p=>`<article class="gov-card"><h2>${escape(p.name)}</h2>${badge(p.status)}<p>${escape(p.description)}</p><dl class="gov-facts"><div><dt>Owner</dt><dd>${escape(p.owner)}</dd></div><div><dt>Tables</dt><dd>${escape(p.primary_tables.join(', '))}</dd></div><div><dt>Metrics</dt><dd>${escape(p.metrics.join(', '))}</dd></div><div><dt>Classification</dt><dd>${escape(p.sensitivity)}</dd></div><div><dt>Consumers</dt><dd>${escape(p.consumers.join(', '))}</dd></div><div><dt>Upstream sources</dt><dd>${escape([...new Set(g.lineage.filter(e=>p.metrics.includes(e.metric)&&e.upstream_asset.startsWith("raw:")).map(e=>e.upstream_asset.slice(4).split(".")[0]))].join(", "))}</dd></div><div><dt>Contracts / readiness at publication</dt><dd>${escape(p.contract_status)} / ${escape(p.readiness)}</dd></div><div><dt>Freshness</dt><dd>Weekly batch; 192-hour limit. See Trust Center for current query-time state.</dd></div><div><dt>Reconciliation coverage</dt><dd>${escape([...new Set(metrics.filter(m=>p.metrics.includes(m.metric_id)).flatMap(m=>m.reconciliation_rule))].join(", ")||"Source controls and semantic computation; no independent three-way total")}</dd></div></dl>${link('metric-catalog','Definitions')} ${link('ai-readiness','Readiness')}</article>`).join('')}</div>`;
 body('contracts').innerHTML=stamp+`<p>Exact schema, required fields, data types, key uniqueness, allowed categories and contract versions are checked before staging. Added or removed fields are breaking under this intentionally strict contract. No silent schema evolution.</p>`+g.contracts.definitions.sources.map(c=>{const r=g.contracts.results.find(r=>r.source===c.source);return detail(c.source+' · '+r.status+' · '+r.records_tested+' rows',`<p>Owner: ${escape(c.owner)} · grain ${escape(c.grain)} · version ${escape(c.version)}</p>`+table(Object.entries(c.columns).map(([column,spec])=>({column,...spec})),[['column','Field'],['type','Type'],['nullable','Nullable'],['sensitivity','Classification'],['allowed_values','Allowed values']])+json(r))}).join('');
 const glossary={Customer:'Master account identifier. Invoiced customers are a distinct subset of master accounts.','Active Customer':'Recency label: at most 90 days since last invoice. This is not a verified churn classification.','Inactive Customer':'The valuable-inactive queue uses >60 days and historical invoiced revenue >= $25,000. The separate segment label Inactive >180 days uses a different threshold.',Vendor:'Supplier master linked to purchase orders; no live ERP connection.', 'Purchase Order':'Procurement header with one or more purchase lines; commitments are unreceived quantities at line cost.',Return:'Physical customer-return event linked to an invoice line. It is not evidence of a posted credit note.',Warehouse:'Synthetic distribution location attached to inventory movements and orders.','Sales Order / Invoice':'Bookings include open/cancelled orders; revenue comes from posted invoices. These populations must not be mixed.'};
 body('glossary').innerHTML=`<div class="gov-grid">${Object.entries(glossary).map(([term,definition])=>`<article class="gov-card"><h2>${escape(term)}</h2><p>${escape(definition)}</p>${link('data-catalog','Related assets')}</article>`).join('')}${metrics.map(m=>`<article class="gov-card"><h2>${escape(m.display_name)}</h2><p>${escape(m.business_definition)}</p>${link('metric-catalog','Governed definition')}</article>`).join('')}</div>`;
 body('ai-readiness').innerHTML=stamp+`<p>Deterministic control assessment: any mandatory failure → Blocked; acknowledged warnings → Conditional; otherwise Ready. No weighted confidence score. Ownership, definition and classification are validated by the metric registry; access coverage is checked by policy.</p><h2>Metrics</h2>`+table(metrics.map(m=>{const d=api.decision(g,m.metric_id);return {Metric:m.display_name,Domain:m.domain,Readiness:d.status==='BLOCKED'?'Blocked':d.status==='WARNING'?'Conditional':'Ready',Reasons:d.failed_controls.length?d.failed_controls.join(', '):d.status==='WARNING'?'Acknowledged synthetic inventory exception':'All mandatory demo controls pass'}}),[['Metric'],['Domain'],['Readiness'],['Reasons']])+`<h2>Domains / data products</h2>`+table(g.products,[['name','Product'],['readiness','At publication'],['metrics','Metrics'],['owner','Owner']])+`<h2>Source datasets</h2>`+table(g.contracts.results.map(r=>({Dataset:r.source,Contract:r.status,Readiness:r.status==='PASS'?'Conditional':'Blocked',Reason:'Dataset is not exposed directly to AI; use its certified metrics.'})),[['Dataset'],['Contract'],['Readiness'],['Reason']]);
 body('reconciliation').innerHTML=stamp+`<p>Independent raw totals → SQLite queries → published values. Any failed measure blocks a new publication and dependent assistant answers. The existing approved artifact remains available.</p>`+data.reconciliation.map(r=>`<article class="gov-card"><div class="gov-card-heading"><h2>${escape(r.Measure)}</h2>${badge(r.Status)}</div><div class="gov-grid">${[['Source',r.RawValue],['Warehouse',r.FactValue],['Published',r.DashboardValue]].map(([title,v])=>`<div><small>${title}</small><strong class="gov-value">${escape(api.format(v,r.Unit))}</strong></div>`).join('')}</div><p>Maximum variance ${Math.max(r.SourceToWarehouseVariance,r.SourceToDashboardVariance).toExponential(3)} · tolerance ${r.Tolerance} ${escape(r.Unit)}. Validated ${escape(g.version_identity.timestamp)}.</p>${detail('Reconciliation evidence',json(r))}</article>`).join('');
 document.querySelector('#quality').insertAdjacentHTML('beforeend',`<h2>Governance observability</h2><p>Failing rows are not summed across controls because the same record can fail several checks. No trend is claimed from a single approved run.</p>`+detail('Versioned control registry · '+g.control_registry_version,table(g.controls,[['control_id','ID'],['name','Control'],['category','Category'],['status','Result'],['asset','Asset'],['records_tested','Tested'],['failing_rows','Failed'],['owner','Owner'],['threshold','Threshold'],['remediation','Remediation'],['last_run','Last run']])));
 const choices=Object.keys(g.policy.roles).map(r=>`<option>${escape(r)}</option>`).join('');
 function showAnswer(result,target){
   target.innerHTML=`<article class="gov-card"><div class="gov-card-heading"><h2>${result.status==='ANSWERED'?'Evidence-backed answer':'Answer withheld'}</h2>${badge(result.status)}</div><p>${escape(result.text)}</p><p class="gov-context">Business cutoff ${escape(result.business_cutoff)} · data version ${escape(result.data_version?.slice(0,16))} · ${escape(result.timestamp)}</p>${result.rows.length?table(result.rows,Object.keys(result.rows[0]).map(k=>[k])):''}<div class="gov-citations">${result.evidence.map(e=>`<button type="button" data-cite="${escape(e.metric_id)}">${escape(e.metric_id)} · v${escape(e.version)}</button>`).join('')} ${link('reconciliation','Reconciliation')} ${link('lineage','Lineage')}</div>${detail('Answer provenance: question → metric → SQL → source → controls',json(result))}</article>`;
   target.querySelectorAll('[data-cite]').forEach(b=>b.onclick=()=>{selectMetric(b.dataset.cite);location.hash='#metric-catalog'});
 }
 body('ai-assistant').innerHTML=stamp+`<div class="gov-card"><h2>Ask the approved data</h2><p>Deterministic local analytical engine — no LLM, no generated SQL. Questions are matched to supported operations; unsupported questions return no answer.</p><label class="gov-field">Demo role simulation — not production authentication<select id="ai-role">${choices}</select></label><form id="ai-form"><label class="gov-field">Your question<input id="ai-question" maxlength="500" required value="What was revenue in 2025?"></label><button type="submit">Ask with evidence</button></form><div class="gov-examples">${api.supported.map(q=>`<button type="button" data-question="${escape(q)}">${escape(q)}</button>`).join('')}</div></div><div id="ai-answer" aria-live="polite"></div>`;
 const ask=()=>{const question=document.querySelector('#ai-question').value;const result=new api.LocalAnalyticalProvider().answer(data,question,document.querySelector('#ai-role').value);showAnswer(result,document.querySelector('#ai-answer'));log('ai_question_evaluated',result);log(result.policy_decision==='ALLOW'?'ai_answer_allowed':'ai_answer_blocked',result)};
 document.querySelector('#ai-form').onsubmit=e=>{e.preventDefault();ask()};document.querySelectorAll('[data-question]').forEach(b=>b.onclick=()=>{document.querySelector('#ai-question').value=b.dataset.question;ask()});
 body('incidents').innerHTML=`<div class="gov-card"><h2>Isolated failure demonstration</h2><p>These scenarios override a copied trust decision. They never write source data, alter the approved artifact, or simulate a successful new publication. Negative pipeline tests separately inject actual source and stage failures.</p><label class="gov-field">Failure scenario<select id="incident-scenario">${Object.keys(api.scenarios).filter(s=>s!=='none').map(s=>`<option value="${s}">${escape(s.replaceAll('_',' '))}</option>`).join('')}</select></label><button type="button" id="run-incident">Evaluate blocked answer</button> <button type="button" id="recover-incident">Restore approved evidence</button><p>Recovery: correct the source or definition, rerun controls, then publish a new approved version. Resetting this demonstration does not fix a real failed pipeline.</p></div><div id="incident-result" aria-live="polite"></div>`;
 const incident=scenario=>{const result=api.answer(data,'What was gross margin?','Executive',scenario);showAnswer(result,document.querySelector('#incident-result'));log(scenario==='none'?'simulation_reset':'failure_simulated',result)};
 document.querySelector('#run-incident').onclick=()=>incident(document.querySelector('#incident-scenario').value);document.querySelector('#recover-incident').onclick=()=>incident('none');
 document.querySelector('#architecture').insertAdjacentHTML('beforeend',`<article class="gov-card"><h2>V2: governed ERP intelligence</h2><div class="gov-architecture">${['Source contracts','Raw / landing','Schema + quality','Normalized staging','Dimensional warehouse','Reconciliation','Semantic registry','Column lineage','Trust decisions','Demo authorization','Dashboard + governed assistant'].map(s=>`<span>${escape(s)}</span>`).join('<b aria-hidden="true">→</b>')}</div><p><b>IMPLEMENTED:</b> contracts, governed SQL, lineage, publication controls, evidence-backed local answers.</p><p><b>SIMULATED / DEMONSTRATED:</b> synthetic ERP, browser role switching, isolated incident controls.</p><p><b>FUTURE ENTERPRISE CAPABILITY:</b> live connectors, private service, Entra ID/OIDC, warehouse RLS, durable security audit and an external LLM provider.</p><a href="https://github.com/Jithendra-data/datrixon/blob/main/documentation/releases/v2.md">V2 release and operating guide →</a></article>`);
 renderTrustCenter();renderAudit();
 document.querySelector('.trust-summary a').href='#trust-center';
}
